version: "3"
services:
  db:
    image: postgres:11.5
    environment:
      POSTGRES_PASSWORD: pswrd
    volumes:
      - ./pgsql-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      RAILS_ENV: development
      BUNDLE_DEPLOYMENT: 0
      BUNDLE_WITHOUT:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: pswrd
    command: bash -c "rm -rf /rails/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails
      - /rails/tmp
      - /rails/log
      - /rails/.git
      - ./vendor/bundle:/usr/local/bundle
    depends_on:
      - db
    env_file:
      - .env
    tty: true
    stdin_open: true
